Import('qt_env')

env = qt_env.Clone()

env.EnableQtModules('Declarative', 'Script')

env.AppendUnique(CPPDEFINES = [ 'INSTALLERMANUAL_LIBRARY' ])

env['CPPPATH'] += [ '.' ]

env.AppendUnique(LIBS = 'shell32')

env.Uic(env.Glob('*.ui'))

lib = env.SharedLibrary('installerManual', env.Glob('*.cpp'))
env.InstallModule(lib)

res = env['QT_USED_MODULES']
Return('res')
